version: 2.1

workflows:
  test-env-vars:
    jobs:
      - print_hello
      - print_world:
          requires:
            - build
            - print_hello
      - body:
      requires:
        - print_world

jobs:
  print_hello:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: "echo hello"
          command: |
            echo "hello"
  print_world:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: "echo world"
          command: |
            echo "world"
  body:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: "echo body"
          command: |
            echo "body"
