version: 2.1

workflows:
  test-env-vars:
    jobs:
      - build
      - print_hello
      - print_world:
          requires:
            - build
            - print_hello

jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: "echo an env var that is part of our project"
          command: |
            echo $MY_ENV_VAR
  print_hello:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: "echo hello"
          command: |
            echo "hello"
  print_world:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: "echo world"
          command: |
            echo "world"
